### ISSUE TITLE
doit not working with latest version of conan

### ISSUE THREAD

**Issue by SinisterMJ** [Ubitrack/ubitrack_release_tools#3]
Since conan 1.19.1, the PackageTester and ConanManager 
from conans.client.cmd.test import PackageTester
from conans.client.manager import ConanManager 

do not exist anymore. Changing the code in workspace/ubitrackWorkspace.py instead to
import conans.client.cmd.test
import conans.client.manager

worked, as conan removed the two classes apparently.

**Comment by FriederPankratz** [comment]
fixed with latest commit
